
spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: "${DB_URL}"
    username: "${DB_USER}"
    password: "${DB_PASSWORD}"
  flyway:
    enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
  application:
    name: reservasalas
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

